### ISSUE TITLE
test 中 From接上游請放第一行

### ISSUE THREAD

**Issue by leo424y** [twgo/DNN-test#1]
https://github.com/twgo/DNN-test/blob/2978699752a6720b8b3f2fdfefe553c40f29e0c1/Dockerfile#L4

老大，我接實驗的設計是把第一行改成接的目標image，故這個請放第一行，感謝

**Comment by sih4sing5hong5** [comment]
我需要囥佇後壁，請你改程式 https://github.com/twgo/twgo-exp/issues/104

**Comment by sih4sing5hong5** [comment]
希望你若看著我有需要，請你體貼一下，先幫我改好抑是揣別的解法。莫等我需要的時陣才催你做

**Comment by leo424y** [comment]
很抱歉，我實在不周到，已改成搜尋並取代，謝謝你指出我的不周。
例： 
https://jenkins.iis.sinica.edu.tw/job/DNN-test/39/console
